name: tnerroT CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        compiler:
          - gcc

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show GCC Version
        shell: bash
        run: |
          gcc --version

      - name: Build Project
        shell: bash
        run: |
          gcc \
            -Wall -Wextra -Werror \
            -Iinclude \
            utils/sha1.c \
            src/bencoder.c \
            src/btypes.c \
            src/main.c \
            src/torrent.c \
            src/tracker.c \
            utils/RFC1738_url_parser.c \
            -lws2_32
            -o tnerroT.exe

      # MAIN BINARY - SMOKE TEST
      - name: Parse Torrent
        shell: bash
        run: |
          ./tnerroT.exe big-buck-bunny.torrent

      # BENCODER TESTS
      - name: Build Bencoder Tests
        shell: bash
        run: |
          gcc \
            -Wall -Wextra -Werror \
            -Iinclude \
            -Itests \
            src/bencoder.c \
            src/btypes.c \
            tests/test_bencoder.c \
            -o test_bencoder.exe

      - name: Run Bencoder Tests
        shell: bash
        run: |
          ./test_bencoder.exe

      # TORRENT PARSER TESTS
      - name: Build Torrent Tests
        shell: bash
        run: |
          gcc \
            -Wall -Wextra -Werror \
            -Iinclude \
            -Itests \
            src/bencoder.c \
            src/btypes.c \
            src/torrent.c \
            utils/sha1.c \
            tests/test_torrent.c \
            src/tracker.c \
            utils/RFC1738_url_parser.c \
            -lws2_32
            -o test_torrent.exe

      - name: Run Torrent Tests
        shell: bash
        run: |
          ./test_torrent.exe big-buck-bunny.torrent