
name: tnerroT CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy: 
      fail-fast : false
      matrix:
        compiler:
          - gcc
          - clang
  
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang

      - name: Build Project with warnings and sanitizers
        run: |
          ${{ matrix.compiler }} \
            -Wall -Wextra -Werror \
            -fsanitize=address,undefined \
            -Iinclude \
            src/bencoder.c \
            src/btypes.c \
            src/main.c \
            src/torrent.c \
            -o tnerroT
      
        # MAIN BINARY - SMOKE TESTING
      - name : Run a Torrnt parse
        run: ./tnerroT big-buck-bunny.torrent

        # BENCODER TESTS
      - name : Build Bencoder Tests
        run : gcc -Iinclude -Itests src/bencoder.c src/btypes.c tests/test_bencoder.c -o test_bencoder

      - name : Run Bencoder Tests
        run : ./test_bencoder

        # TORRENT PARSER TESTS
      - name : Build Torrent Tests
        run : gcc -Iinclude -Itests src/bencoder.c src/btypes.c src/torrent.c tests/test_torrent.c -o test_torrent
      
      - name : Run Torrent Tests
        run : ./test_torrent big-buck-bunny.torrent